//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerSkySADETests {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitTestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitTestResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamerSkySADETests.UnitTestResource", typeof(UnitTestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似         &lt;li&gt;
        ///          &lt;div class=&quot;img&quot;&gt;&lt;a href=&quot;文章链接&quot; target=&quot;_blank&quot;&gt;
        ///            &lt;img src=&quot;图像链接&quot; alt=&quot;文章标题&quot;  width=&quot;200&quot; height=&quot;110&quot; class=&quot;pe_u_thumb&quot; border=&quot;0&quot;&gt;
        ///          &lt;/a&gt;&lt;/div&gt;
        ///          &lt;div class=&quot;con&quot;&gt;
        ///            &lt;div class=&quot;tit&quot;&gt;&lt;a href=&quot;文章链接&quot; target=&quot;_blank&quot; title=&quot;文章标题&quot;&gt;文章标题&lt;/a&gt;&lt;/div&gt;
        ///            &lt;div class=&quot;txt&quot;&gt;文章描述&lt;/div&gt;
        ///            &lt;div class=&quot;tme2&quot;&gt;&lt;div class=&quot;time&quot;&gt;发布时间&lt;/div&gt;&lt;div class=&quot;pls cy_comment&quot; data-sid=&quot;1094068&quot;&gt;&lt;/div&gt;&lt;/div&gt;
        ///          &lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string ConvertToArticleTestResource {
            get {
                return ResourceManager.GetString("ConvertToArticleTestResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;title&gt;搞笑趣闻 _ 游民星空 Gamersky.com&lt;/title&gt;
        ///  &lt;meta name=&quot;keywords&quot; content=&quot;&quot; /&gt;
        ///  &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///  &lt;script src=&quot;//j.gamersky.com/g/jquery-1.8.3.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;//j. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FullTestResource {
            get {
                return ResourceManager.GetString("FullTestResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;ul class=&quot;pictxt contentpaging&quot; data-nodeid=&quot;20113&quot; data-isnodeid=&quot;true&quot;&gt;
        ///      
        ///            
        ///          
        ///      
        ///        &lt;li&gt;
        ///          &lt;div class=&quot;img&quot;&gt;&lt;a href=&quot;https://www.gamersky.com/ent/201808/1094495.shtml&quot; target=&quot;_blank&quot;&gt;
        ///            &lt;img src=&quot;https://imgs.gamersky.com/upimg/2018/201809011826498967.jpg&quot; alt=&quot;当代两性社交礼仪 令人流口水的囧图&quot;  width=&quot;200&quot; height=&quot;110&quot; class=&quot;pe_u_thumb&quot; border=&quot;0&quot;&gt;
        ///          &lt;/a&gt;&lt;/div&gt;
        ///          &lt;div class=&quot;con&quot;&gt;
        ///            &lt;div class=&quot;tit&quot;&gt;&lt;a href=&quot;https://www.gamersky. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetCatalogListTestResource {
            get {
                return ResourceManager.GetString("GetCatalogListTestResource", resourceCulture);
            }
        }
    }
}
